import { type Metadata } from "next";
import NavigateHeader from "@/components/NavigateHeader";
import { Layout } from "@/components/Layout";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <Layout
      header={
        <NavigateHeader />
      }
    >
      {children}
    </Layout>
  );
}
