import { type Metadata } from "next";
import Header from "@/widgets/Header";
import Container from "@/components/Container";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <Header />
      <Container>{children}</Container>
    </>
  );
}
