import { type Metadata } from "next";
import Hero from "./_components/Hero";
import QuickActions from "./_components/QuickActions";
import Section from "@/components/Section";
import { Input } from "@/components/ui/input";
import { Search } from "lucide-react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
   <div className="space-y-6">
        <Section>
          <div className="relative">
           <Search className="absolute top-1/2 left-3 h-4 w-4 -translate-y-1/2 transform text-gray-400" />
            <Input
              placeholder="Пошук страв та напоїв..."
              className="h-12 rounded-xl pl-10"
            />
          </div>
        </Section>
        <Hero />
          {children}
        <QuickActions />
      </div> 
  );
}
