import { type Metadata } from "next";
import { Layout } from "./_components/Layout";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function CustomerLayout({
  children,
  header
}: Readonly<{ children: React.ReactNode, header?: React.ReactNode }>) {
  return <Layout header={header}>{children}</Layout>;
}
